### ISSUE TITLE
Uzupełnij dokumentacje API

### ISSUE THREAD

**Issue by wsliwa** [Tomasz-Zdeb/Software-Engineering-Class-Project#105]
## Kryteria Akceptacji

- [x] Opis Flask'a został dodany
- [x] Opis Flask restx został dodany
- [x] Zmiany zostały zacommitowane
- [x] Commit ze zmianami znajduje się na branchu `master`

**Comment by wsliwa** [comment]
W dokumentacji API brakuję bibliotek Flask i Flask-RESTX. Jakby była jeszcze jakaś biblioteka do opisania to ją podajcie w komentarzu.

**Comment by wsliwa** [comment]
Propopnowany opis dla Flask'a:

## Flask
Flask to mikro-framework napisany w języku Python, który pozwala na tworzenie aplikacji internetowych. 

Charakteryzuje się:
- **Prostotą**: Jest łatwy w nauce i zrozumieniu, nawet dla początkujących programistów.
- **Elastycznością**: Pozwala na dużą swobodę w konfiguracji i rozbudowie aplikacji, oferując modularną strukturę.
- **Skalowalnością**: Jest odpowiedni dla projektów o różnym stopniu złożoności, od prostych stron do rozbudowanych systemów.
- **Wsparciem społeczności**: Dysponuje bogatą bazą zasobów, ciągłym rozwojem i aktualizacjami dzięki zaangażowanej społeczności.
- **Integracją z Pythonem**: Zapewnia doskonałe połączenie z innymi bibliotekami i narzędziami Pythona, co ułatwia rozwój i utrzymanie aplikacji.

W naszym projekcie wykorzystujemy Flask do budowy API, które służy komunikacji pomiędzy frontendem a backendem aplikacji. Dzięki użyciu Flask w naszym API, możemy szybko implementować nowe funkcje, a także łatwo aktualizować i modyfikować istniejące elementy.

**Comment by wsliwa** [comment]
Proponowany opis dla Flask-RESTX:

## Flask-RESTX

Flask-RESTx to rozszerzenie dla Flask, które ułatwia tworzenie szybkich, elastycznych i łatwych w utrzymaniu API opartych na architekturze REST. Zaprojektowany z myślą o prostocie i wydajności, Flask-RESTx wprowadza zestaw narzędzi, które pozwalają na szybką implementację, testowanie oraz dokumentowanie API.

Flask-RESTx charakteryzuje się:

- **Prostotą**: Ułatwia tworzenie API opartych na architekturze REST, oferując czytelne i zwięzłe struktury kodu.
- **Automatyczna dokumentacja**: Wspiera automatyczne generowanie interaktywnej dokumentacji API z wykorzystaniem standardu OpenAPI.
- **Walidacja danych**: Zapewnia wbudowane mechanizmy walidacji danych, co pozwala na utrzymanie spójności i poprawności danych wejściowych i wyjściowych.
- **Przejrzystość**: Dzięki zastosowaniu dekoratorów i przestrzeni nazw, Flask-RESTx pozwala na łatwe rozróżnienie poszczególnych zasobów i funkcji API.
- **Integracja z Flask**: Jako rozszerzenie Flask, Flask-RESTx doskonale współpracuje z innymi elementami frameworka, umożliwiając płynną integrację z istniejącymi aplikacjami opartymi na Flask.

W projekcie, głównym zastosowaniem Flask-RESTx będzie automatyczna generacja dokumentacji Swagger dla endpointów API. Korzystając z interaktywnej dokumentacji API opartej na standardzie OpenAPI, Flask-RESTx pozwala na łatwe zrozumienie, eksplorację i testowanie endpointów API przez użytkowników oraz programistów. Dzięki temu, proces rozwijania i aktualizowania API jest znacznie uproszczony, a czas potrzebny na tworzenie ręcznej dokumentacji jest zredukowany. Automatyczna dokumentacja pozwala także na utrzymanie jej aktualności i spójności z bieżącym stanem endpointów.

**Comment by Tomasz-Zdeb** [comment]
Wg. mnie obie przedstawione propozycje są w porządku, można commitować i tworzyć PRa 👍

**Comment by wsliwa** [comment]
Wszystkie zadania zostały wykonane. Zamykam.
