### ISSUE TITLE
Przeprowadź research na temat realizacji kwestii związanych z utrzymywaniem sesji i autentykacji użytkowników w Flasku

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Software-Engineering-Class-Project#108]
## Kryteria Akceptacji

- [x] Research został przeprowadzony, a jego wyniki umieszczone w poniższym issue
- [ ] Zostały wybrane frameworki pomocnicze do utrzymywania i zarządzania sesją (jeśli konieczne)

**Comment by jackpie2** [comment]
Myślę, że najprościej byłoby użyć [JSON Web Tokens ](https://auth0.com/docs/secure/tokens/json-web-tokens) i biblioteki [flask-jwt-extended](https://flask-jwt-extended.readthedocs.io/en/stable/basic_usage/). Podczas logowania użytkownika, generowany i zwracany byłby token, wykorzystywany do wszelkich autoryzacji i identyfikacji użytkownika.

W najprostszej implementacji mielibyśmy token z sztywno ustawionym czasem wygaśnięcia i w przypadku wylogowania użytkownika przed czasem wygaśnięcia token byłby usuwany po stronie klienta. Takie podejście nie sprawia jednak, że token byłby nieważny dla API i jeśli udałoby się go zdobyć/zapisać, to pomimo wylogowania mógłby być dalej używany do autoryzacji użytkownika: [link](https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#no-built-in-token-revocation-by-the-user). Jest parę rozwiązań tego problemu, można np. utworzyć tabelę w bazie danych przechowującą tokeny, które nie powinny być dalej używane. Proponowałbym jednak zacząć od tego podstawowego założenia i jeśli starczy czasu, to ewentualnie dodać takie dodatkowe zabezpieczenia.

**Comment by wsliwa** [comment]
Jest jeszcze Flask-Session, ale z tego co czytałem dla API lepszym rozwiązaniem jest właśnie użycie tokenów jwt.

**Comment by jackpie2** [comment]
W związku ze zbliżającym się deadlinem milestona, myślę że można przejść już do implementacji wspomnianego mechanizmu w oparciu o JWT i flask-jwt-extended.
