### ISSUE TITLE
Opisz proces integracji Draw.io z Repo/GitHubem

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Software-Engineering-Class-Project#11]
## Kryteria Akceptacji Zadania

- [x] Proces integracji Draw.io z Repo/GitHubem jest opisany (w postaci punktów)
- [x] Opis procesu znajduje się w komentarzu niniejszego Issue

**Comment by KarolBochenek** [comment]
W celu posiadania dostępu do diagramu znajdującego się w naszym repo musimy wykonać następujące kroki:

1. Wejść na stronę https://www.diagrams.net/
2. Kliknąć "Start"
3. Z sześciu dostępnych opcji do zapisania diagramu wybieramy Github
4. Wybieramy "Otwórz istniejący diagram"
5. Wymagana jest autoryzacja na Github, klikamy "Autoryzuj"
6. W nowym oknie logujemy się na Github (tak, apka jest legitna)
7. Po zalogowaniu się zezwalamy na autoryzację
8. Wracamy do pola do otworzenia diagramu, wybieramy "Otwórz istniejący diagram"
9. Z listy repo wybieramy nasz projekt "Tomasz-Zdeb/Software-Engineering-Class-Project"
10. Jeśli istnieje jakiś branch, teraz możemy go wybrać
11. Wybieramy odpowiedni katalog, w naszym przypadku database/
12. Wybieramy plik z rozszerzeniem .drawio
13. W przypadku próby zapisania zmian program będzie chciał kolejną autoryzację co oznacza zainstalowanie draw.io jako Github App, godzimy się na to.
14. Ważne! Każda zapisana zapisanie zmian wiąże się z commitem

**Comment by Tomasz-Zdeb** [comment]
Jeżeli instrukcja jest kompletna, to zadanie jest wykonane i powinno zostać zamknięte
