### ISSUE TITLE
Zweryfikuj i (potencjalnie) popraw skrypt wprowadzający testowe dane do bazy danych

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Software-Engineering-Class-Project#115]
Obecnie `insert-dummies.sql` wprowadza dane w następujący sposób:
```sql
INSERT INTO public.note VALUES (1, NULL, 'titletest', 'desctest', 'bodytest', '2023-03-04 01:00:00', '2023-03-04 02:00:00');
```

Wydaje mi się, że podanie wprost ID (w tym przypadku notatki) omija autoinkrementację, w rezultacie czego przy próbie wprowadzenia notatki przez API pojawia się błąd, przez to że SQLAlchemy próbuje korzystać z autoinkrementacji i nadawać ID, które jest już zajęte przez testowe dane:
```
DETAIL:  Key (note_id)=(3) already exists.
```

Jeśli testowe dane mają pozostać, to prosiłbym o weryfikację tej hipotezy, ponieważ problem ten uniemożliwia w pewnym stopniu korzystanie z aplikacji w dockerze.

## Kryteria Akceptacji

- [x] Problem został zweryfikowany
- [x] Rozwiązanie problemu zostało zaimplementowane
- [x] Zmiany zostały zacommitowane
- [ ] Commit ze zmianami znajduje się na branchu `master`

**Comment by jackpie2** [comment]
@KarolBochenek

**Comment by KarolBochenek** [comment]
Dzięki, przyjrzę się temu

**Comment by KarolBochenek** [comment]
@jackpie2 Czy mógłbyś sprawdzić na [tym](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/tree/115-zweryfikuj-i-potencjalnie-popraw-skrypt-wprowadzaj%C4%85cy-testowe-dane-do-bazy-danych) branchu, czy SQLAlchemy dalej wywala ten błąd? Wydaje mi się, że teraz powinno wszystko być zgodne z autoinkrementacją.

**Comment by jackpie2** [comment]
Tak, zaraz się temu przyjrzę
