### ISSUE TITLE
Zintegruj Draw.io z Repo/GitHubem

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Software-Engineering-Class-Project#12]
## Kryteria Akceptacji Zadania

- [x] **Draw.io** jest zintegrowane z **Repo/GitHubem**
- [ ] Zmiany w diagramach w Draw.io są commitowane na dedykowany Branch

## Wskazówki

- Instrukcje dotyczące implementacji znajdują się w Issue: #11

**Comment by KarolBochenek** [comment]
@Tomasz-Zdeb Żebym mógł zintegrować draw io musi mieć ono autoryzację na repo, a z tego, co widzę tylko ty możesz to zrobić jako właściciel repo. Wejdź proszę tutaj: https://github.com/apps/draw-io-app i autoryzuj aplikację dla naszego repo. Dzięki

**Comment by Tomasz-Zdeb** [comment]
Zrobione
