### ISSUE TITLE
Stwórz endpointy do tagowania notatek.

### ISSUE THREAD

**Issue by wsliwa** [Tomasz-Zdeb/Software-Engineering-Class-Project#125]
## Kryteria Akceptacji

- [x] Struktura endpointów została omówiona
- [ ] Zmiany zostały zaakceptowane
- [ ] Commit ze zmianami znajduje się na branchu `master`
- [ ] Zmiany zostaly przetestowane
- [ ] Test evidence zostało dołączone do Issue

**Comment by wsliwa** [comment]
# Propozycja endpointów

## Tagi dla notatek

### Tworzenie tagu dla notatki

**Endpoint:** `/note/tags`

**Metoda:** `POST`

**Opis:** Tworzy nowy tag dla danej notatki.

**Parametry:**

- `note_id` (wymagane, liczba całkowita): ID notatki, dla której tworzony jest tag.
- `tag_name` (wymagane, ciąg znaków): Nazwa taga.

**Przykładowe zapytanie:**
POST /note/tags

```
{
"note_id": 1,
"tag_name": "Ważne"
}
```

**Przykładowe odpowiedzi:**

1. Pomyślne utworzenie tagu

Kod statusu HTTP: `201 Created`

```
{
"message": "Tag 'Important' has been successfully created for the note with ID 1.",
"tag_id": 12
}
```

2. Błędne body zapytania

Kod statusu HTTP: `400 Bad Request`

```
{
"message":  "Invalid request body. Ensure that note_id and tag_name are present and in the correct format."
}
```

3. Nie znaleziona notatki

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Note with ID 1 not found."
}
```

4. Nieprawidłowy token JWT

HTTP status code: `422 Invalid token`

```
{
"message": "Invalid JWT token. Please log in again."
}
```

5. Niewystarczające uprawnienia

HTTP status code: `403 Forbidden`

```
{
"message": "You do not have permission to create tags for this note."
}
```

### Usuwanie taga dla notatki

**Endpoint:** `/note/tags/{tag_id}`

**Metoda:** `DELETE`

**Opis:** Usuwa tag o podanym ID dla notatki.

**Parametry:**

- `tag_id` (wymagane, liczba całkowita): ID taga do usunięcia.

**Przykładowe zapytanie:** DELETE /note/tags/1

**Przykładowe odpowiedzi:**

1. Pomyślnie usunięto tag

HTTP status code: `200 OK`

```
{
"message": "Tag with ID 1 has been successfully deleted."
}
```

3. Nie znaleziono tagu

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Nie znaleziono tagu o ID 1."
}
```

4. Nieprawidłowy token JWT

Kod statusu HTTP: `422 Invalid token`

```
{
"message": "Nieprawidłowy token JWT. Proszę zalogować się ponownie."
}
```

5. Niewystarczające uprawnienia

Kod statusu HTTP: `403 Forbidden`

```
{
"message": "Nie masz uprawnień do usuwania tagów dla tej notatki."
}
```

### Pobieranie tagów notatki

**Endpoint:** `/note/{note_id}/tags`

**Metoda:** `GET`

**Opis:** Pobiera listę tagów przypisanych do notatki o podanym ID.

**Parametry:**

- `note_id` (wymagane, liczba całkowita): ID notatki, dla której pobierane są tagi.

**Przykładowe zapytanie:** GET /note/1/tags

**Przykładowe odpowiedzi:**

1. Pomyślne pobranie tagów notatki

Kod statusu HTTP: `200 OK`

```
{
"tags": [
  {
    "tag_id": 1,
    "note_id": 1,
    "tag_name": "Ważne"
  },
  {
    "tag_id": 2,
    "note_id": 1,
    "tag_name": "Priorytet"
  }
 ]
}
```

2. Nie znaleziono notatki

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Nie znaleziono notatki o ID 1."
}
```

3. Nieprawidłowy token JWT

Kod statusu HTTP: `422 Invalid token`

```
{
"message": "Nieprawidłowy token JWT. Proszę zalogować się ponownie."
}
```

4. Niewystarczające uprawnienia

Kod statusu HTTP: `403 Forbidden`

```
{
"message": "Nie masz uprawnień do wyświetlania tagów dla tej notatki."
}
```

### Aktualizowanie taga dla notatki

**Endpoint:** `/note/tags/{tag_id}`

**Metoda:** `PUT`

**Opis:** Aktualizuje tag o podanym ID dla notatki.

**Parametry:**

- `tag_id` (wymagane, liczba całkowita): ID taga do aktualizacji.
- `tag_name` (opcjonalne, ciąg znaków): Nowa nazwa taga.

**Przykładowe zapytanie:** PUT /note/tags/1

```
{
"tag_name": "Nowa nazwa"
}
```

**Przykładowe odpowiedzi:**

1. Pomyślne zaktualizowanie taga

Kod statusu HTTP: `200 OK`

```
{
"tag_id": 1,
"note_id": 1,
"tag_name": "Nowa nazwa"
}
```

2. Nie znaleziono taga

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Nie znaleziono taga o ID 1."
}
```

3. Nieprawidłowy token JWT

Kod statusu HTTP: `422 Invalid token`

```
{
"message": "Nieprawidłowy token JWT. Proszę zalogować się ponownie."
}
```

4. Nieprawidłowe ciało zapytania

Kod statusu HTTP: `400 Bad Request`

```
{
"message": "Nieprawidłowe ciało zapytania. Upewnij się, że tag_name jest obecne i ma poprawny format."
}
```

5. Niewystarczające uprawnienia

Kod statusu HTTP: `403 Forbidden`

```
{
"message": "Nie masz uprawnień do aktualizacji tego taga."
}
```

**Comment by jackpie2** [comment]
W sumie to chyba gdzieś to zostało przeoczone na etapie projektowania, ale do tej pory endpointy zakładały przekazywanie wszystkich danych w jsonie/argumentach (w tym np. danych identyfikujące dany zasób). 

Jeżeli istnieje tylko jeden zasób identyfikowalny przez dane ID, to pewnie najbardziej standardowym podejściem jest dostęp do niego za pomocą parametrów ścieżki, tak jak w powyższej propozycji (np. `/note/tags/{tag_id}`). Być może dobrze byłoby ujednolicić to podejście i albo zamienić konwencje w obecnym endpoincie note na identyfikowanie notatki przez np. `/note/{id}`, zamiast `?id=1` lub przekazywania id w jsonie albo dostosować projekt powyżej opisanego endpointu do już istniejącej implementacji. Jedno lub drugie podejście nie różni się w sumie diametralnie jak chodzi o funkcjonowanie API i jest bardziej decyzją dotyczącą konwencji. 

Zapraszam do dyskusji na temat tego, której konwencji powinniśmy się trzymać @Tomasz-Zdeb @wsliwa i która bardziej ułatwi tworzenie frontu @PWWP

**Comment by wsliwa** [comment]
@jackpie2  
Jako, że już zaczęliśmy implementować w jeden sposób, to pewnie lepiej, żeby tu zmienić. Na jutro zrobię poprawioną propozycje.

**Comment by PWWP** [comment]
Tak naprawdę bez różnicy, byle by tylko nie mixować pomiędzy sobą, więc proponuje zostać przy poprzedniej konwencji lub zmienić wszystko.

**Comment by wsliwa** [comment]
# Propozycja endpointów

## Tagi dla notatek

### Tworzenie tagu dla notatki

**Endpoint:** `/note/tags`

**Metoda:** `POST`

**Opis:** Tworzy nowy tag dla danej notatki.

**Parametry:**

- `note_id` (wymagane, liczba całkowita): ID notatki, dla której tworzony jest tag.
- `tag_name` (wymagane, ciąg znaków): Nazwa tagu.

**Przykładowe zapytanie:**
POST /note/tags

```
{
"note_id": 1,
"tag_name": "Ważne"
}
```

**Przykładowe odpowiedzi:**

1. Pomyślne utworzenie tagu

Kod statusu HTTP: `201 Created`

```
{
"message": "Tag 'Ważne' has been successfully created.",
"tag_id": 12
}
```

2. Błędne body zapytania

Kod statusu HTTP: `400 Bad Request`

```
{
"message":  "Invalid request body. Ensure that note_id and tag_name are present and in the correct format."
}
```

3. Nie znaleziona notatki

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Note with ID 1 not found."
}
```

4. Nieprawidłowy token JWT

HTTP status code: `422 Invalid token`

```
{
"message": "Invalid JWT token. Please log in again."
}
```

5. Niewystarczające uprawnienia

HTTP status code: `403 Forbidden`

```
{
"message": "You do not have permission to create tags for this note."
}
```

### Usuwanie tagu dla notatki

**Endpoint:** `/note/tags`

**Metoda:** `DELETE`

**Opis:** Usuwa tag o podanym ID dla notatki.

**Parametry:**

- `tag_id` (wymagane, liczba całkowita): ID tagu do usunięcia.

**Przykładowe zapytanie:** 
DELETE /note/tags

```
{
"tag_id": 1
}
```

**Przykładowe odpowiedzi:**

1. Pomyślnie usunięto tag

HTTP status code: `200 OK`

```
{
"message": "Tag with ID 1 has been successfully deleted."
}
```

3. Nie znaleziono tagu

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Tag with ID 1 not found."
}
```

4. Nieprawidłowy token JWT

Kod statusu HTTP: `422 Invalid token`

```
{
"message": "Invalid JWT token."
}
```

5. Niewystarczające uprawnienia

Kod statusu HTTP: `403 Forbidden`

```
{
"message": "You do not have permission to delete tags for this note."
}
```

### Pobieranie tagów notatki

**Endpoint:** `/note/{note_id}/tags`

**Metoda:** `GET`

**Opis:** Pobiera listę tagów przypisanych do notatki o podanym ID.

**Parametry:**

- `note_id` (wymagane, liczba całkowita): ID notatki, dla której pobierane są tagi.

**Przykładowe zapytanie:** 
GET /note/tags

```
{
"note_id": 1
}
```

**Przykładowe odpowiedzi:**

1. Pomyślne pobranie tagów notatki

Kod statusu HTTP: `200 OK`

```
{
"tags": [
  {
    "tag_id": 1,
    "note_id": 1,
    "tag_name": "Ważne"
  },
  {
    "tag_id": 2,
    "note_id": 1,
    "tag_name": "Priorytet"
  }
 ]
}
```

2. Nie znaleziono notatki

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Note with ID 1 not found."
}
```

3. Nieprawidłowy token JWT

Kod statusu HTTP: `422 Invalid token`

```
{
"message": "Invalid JWT token."
}
```

4. Niewystarczające uprawnienia

Kod statusu HTTP: `403 Forbidden`

```
{
"message": "You do not have permission to view tags for this note."
}
```

5.  Błędne body zapytania

Kod statusu HTTP: `400 Bad Request`

```
{
"message":  "Invalid request body. Ensure that note_id is present and in the correct format."
}
```

### Aktualizowanie tagu dla notatki

**Endpoint:** `/note/tags`

**Metoda:** `PUT`

**Opis:** Aktualizuje tag o podanym ID dla notatki.

**Parametry:**

- `tag_id` (wymagane, liczba całkowita): ID tagu do aktualizacji.
- `tag_name` (opcjonalne, ciąg znaków): Nowa nazwa tagu.

**Przykładowe zapytanie:** PUT 
/note/tags

```
{
"tag_id": 1,
"tag_name": "Nowa nazwa"
}
```

**Przykładowe odpowiedzi:**

1. Pomyślne zaktualizowanie tagu

Kod statusu HTTP: `200 OK`

```
{
"tag_id": 1,
"note_id": 1,
"tag_name": "Nowa nazwa"
}
```

2. Nie znaleziono tagu

Kod statusu HTTP: `404 Not Found`

```
{
"message": "Note with ID 1 not found."
}
```

3. Nieprawidłowy token JWT

Kod statusu HTTP: `422 Invalid token`

```
{
"message": "Invalid JWT token."
}
```

4. Nieprawidłowe ciało zapytania

Kod statusu HTTP: `400 Bad Request`

```
{
"message": "Invalid request body."
}
```

5. Niewystarczające uprawnienia

Kod statusu HTTP: `403 Forbidden`

```
{
"message": "You do not have permission to update this tag."
}
```

**Comment by jackpie2** [comment]
Co do pobierania tagów notatki, to może chciałbyś dodać to po prostu do istniejącego endpointa note? Wtedy nie trzeba byłoby robić dodatkowych zapytań żeby pobrać tagi. No chyba, że frontend wolałby mieć osobny endpoint do dyspozycji w tej kwestii (@PWWP)
