### ISSUE TITLE
Popraw endpoint /register

### ISSUE THREAD

**Issue by PWWP** [Tomasz-Zdeb/Software-Engineering-Class-Project#130]
API nie blokuje tworzenia użytkownika z pustym loginem/hasłem.

![obraz](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/6884361/46c24d69-61d6-4522-bb8f-2ad674c1d9a9)

## Kryteria Akceptacji

- [ ] Po wysłaniu zapytania API powinno zwrócić błąd informujący o niepoprawnym loginie/haśle.
- [ ] Zmiany zostały zacommitowane
- [ ] Commit ze zmianami znajduje się na branchu `master`
- [ ] Zmiany zostaly przetestowane
- [ ] Test evidence zostało dołączone do Issue

**Comment by jackpie2** [comment]
Za chwilę wrzucę do tego poprawkę.
