### ISSUE TITLE
Dodaj funkcjonalność do endpointu tworzenia notatki

### ISSUE THREAD

**Issue by PWWP** [Tomasz-Zdeb/Software-Engineering-Class-Project#133]
Najprościej dla frontu było by dodać endpoincie wysyłania nowej notatki nie tylko możliwość dodania za pomocą id katalogu ale nazwy katalogu. Jeżeli nazwa nie istnieje to API zwróci komunikat o tym, że nazwa katalogu nie istnieje. 
W tym przypadku należy zaprogramować wymóg podania catalog_id lub catalog_name oraz nigdy łącze podanie obydwu fieldów.

Alternatywnie trzeba by stworzyć nowy endpoint posiadający w parametrach nazwę katalogu a zwracający id katalogu (więcej zabawy na froncie)

Zapraszam do dyskusji - @wsliwa @xQuarellox @jackpie2 @jackpie2 @k4ciek 

## Kryteria Akceptacji
- [x] Zmiany zostały zacommitowane
- [x] Commit ze zmianami znajduje się na branchu `master`
- [x] Zmiany zostaly przetestowane
- [x] Test evidence zostało dołączone do Issue

**Comment by jackpie2** [comment]
![obraz](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/66798628/aded034d-16b8-4856-8a87-dbce04ce2608)

Przy obecnym designie bazy danych wydaje mi się, że żeby jednoznacznie znaleźć katalog danego użytkownika po nazwie trzeba by wnioskować na podstawie 3 tabeli: `note`, `user_note` i `catalog`, można wtedy zobaczyć jakie katalogi są przydzielone do notatek i sprawdzić czy dana nazwa się w nich zawiera, trzeba wtedy jednak przeglądać wszystkie notatki danego użytkownika. Nie da się tego zrobić tylko na podstawie tabeli catalog bo nazwy nie są i nie mogą być unikalne, żeby użytkownicy nie mogli sobie ich zajmować. Wydaje mi się, że najłatwiej dla backendu byłoby gdyby była jakaś tabela, identyfikująca właścicieli danych katalogów (tak jak np. user_note), wtedy można by zrobić jakiegoś joina dla danego użytkownika z tabelą catalog i sprawdzić czy istnieje już katalog o wybranej nazwie. Być może da się to zrobić prościej lub lepiej, ale to może bardziej już pytanie do @KarolBochenek. Dobrze jakbyś też dał znać, czy w ogóle byłbyś chętny na takie modyfikacje.

Inną kwestią jest jeszcze to, że w obecnej implementacji db nie ma pola na nazwę, nie wiem czy to przeoczenie czy intencjonalnie:
![obraz](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/66798628/ad2cdd29-7dd7-4242-9ac2-62fbd6f0bdb7)

**Comment by PWWP** [comment]
Chyba, że zakładamy nazwa katalogu == id_katalogu
To bardzo duże uproszczenie ale teoretycznie zamyka temat

**Comment by jackpie2** [comment]
No według mnie moglibyśmy tak założyć wstępnie, zdecydowanie zaoszczedzilibyśmy na tym czas. No chyba że byłby jakis sprzeciw ze strony @Tomasz-Zdeb

**Comment by Tomasz-Zdeb** [comment]
Jak najbardziej. Możemy też oczywiście opisać w dokumentacji dlaczego wybraliśmy takie podejście

**Comment by KarolBochenek** [comment]
@jackpie2 Jeśli możliwe jest ustalenie, że nazwa katalogu = id katalogu i to będzie działać, to zostawiłbym bez modyfikacji ze względu na czas. Co do braku 'name' w skrypcie tworzenia tabeli catalog, to rzeczywiście nie ma tego, nie wiem jak mogłem to przeoczyć. Poprawiam. Przy okazji sprawdzę jeszcze raz, czy wszystkie inne kolumny są tworzone zgodnie z diagramem ERD.

**Comment by jackpie2** [comment]
@KarolBochenek nie widziałem wcześniej tego edita. Póki co nie korzystałem, narazie implementacja zakłada zwykłych użytkowników jedynie. Było gdzieś ustalane co mógłby robić taki admin?

**Comment by PWWP** [comment]
Wracając do nazwy katalogu jakie finalnie rozwiązanie proponujecie?

**Comment by Tomasz-Zdeb** [comment]
Jasne, w obecnej sytuacji nie ma na to czasu. Ja bym pozostał przy jednym rodzaju użytkowników.

**Comment by jackpie2** [comment]
Rozwiązane w #147, jakby były jakieś problemy z tym to otwórz znowu albo utwórz nowy issue.
