### ISSUE TITLE
Zdecyduj o implementacji i designie folderów

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Software-Engineering-Class-Project#140]
Wcześniej dyskutowane w ramach #127 i #137.

Na chwilę obecną są chyba dwa rozwiązania, albo obecny system bez modyfikacji i operujący tylko na ID jako nazwie folderu, albo drugi zaproponowany na spotkaniu, który z tego co rozumiem nie korzystałby z relacji w bazie danych tylko byłby wpisem typu string w tabeli notatki. To by wymagało oczywiście edytowania endpointu `/note` i DB. Tutaj padła też propozycja zagnieżdżonych folderów w stylu `/folder1/folder2`, to by już pewnie wymagało większego edytowania #137, bo jest zrobione typowo pod strukturę z #127, ale poza tym wydaje mi się że działałoby identycznie do zwykłego wpisu typu string w tabeli note.

Zapraszam do dyskusji @PWWP @KarolBochenek i wszystkie inne zainteresowane osoby.

Dopóki ta kwestia nie zostanie ustalona to poczekam z mergowaniem #137.

## Kryteria Akceptacji

- [ ] Sposób implementacji został wybrany

**Comment by PWWP** [comment]
Proponuję:

Opcja A: Zmieniamy field catalog_id na catalog_name w note i traktujemy go jako nazwę folderu
Opcja B: Obsługujemy tworzenie, usuwanie i edytowanie nazw katalogów (wymaga po stronie Backendu API do katalogów i konkretnej implementacji po stronie frontu - w tym przypadku prosił bym o uwolnienie wymogu podawania w tworzeniu /note catalog_id, i domyślnie przyjmowany był by BASE_DIR danego użytkownika)
Opcja C: Jest to uproszczenie B - zamiast tworzenia nowego API do katalogów to przy tworzeniu notatki zamiast catalog_id podajemy catalog_name na którego backend decyduje jakie jest ID katalogu oraz czy ewentualnie trzeba stworzyć taki katalog.

**Comment by jackpie2** [comment]
Najbardziej przekonuje mnie opcja C. Trochę wtedy tabela z katalogami staje się przekombinowana, ale za to to rozwiązanie nie wymaga zmiany struktur notatki ani modyfikacji DB.

**Comment by jackpie2** [comment]
Jak nie pojawią się głosy sprzeciwu to implementuje to jak tylko rozwiązane zostanie #142

**Comment by PWWP** [comment]
> Najbardziej przekonuje mnie opcja C. Trochę wtedy tabela z katalogami staje się przekombinowana, ale za to to rozwiązanie nie wymaga zmiany struktur notatki ani modyfikacji DB.

Można powiedzieć, że wtedy tabela z katalogami jest na zapas - jeżeli projekt był by rozwijany dalej to chociażby funkcjonalności tj. udostępnianie folderów potrzebowało by takiej tabeli.
