### ISSUE TITLE
Przedyskutuj kwestię hashowania haseł między DB a API

### ISSUE THREAD

**Issue by KarolBochenek** [Tomasz-Zdeb/Software-Engineering-Class-Project#143]
Zapytałem chatGPT o kwestię salted hashing haseł w postgreSQL. Dał taką odpowiedź: 
![Screenshot_2023-05-30-20-45-20-130_com android chrome](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/95887356/d662f531-d2b0-4316-b7d3-56be5d4f507a)
Następnie zapytałem o powiązanie tego z API we Flasku:
![Screenshot_2023-05-30-20-49-10-105_com android chrome](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/95887356/0678b284-b9b7-4a0c-b6d3-0fa102abbc79)
![Screenshot_2023-05-30-20-49-17-588_com android chrome](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/95887356/e8562db9-7305-40cc-a836-6f02874efb4f)

Wygląda na to, że hashowanie hasła jak i salt powinien być wykonany na API a do DB wysyłane będzie już zahashowane hasło razem z saltem. W obecnej wersji DB tabela user_table ma już kolumny 'salt' i 'hashed_password'. Proszę team API o jakąś dyskusję w tym temacie, czy rozwiązanie proponowane przez GPT będzie dla nas odpowiednie. @jackpie2 @wsliwa @xQuarellox 

## Kryteria Akceptacji

- [x] Kwestia została przedyskutowana

**Comment by KarolBochenek** [comment]
Teraz zobaczyłem, że powstało #142 i w sumie tam moglibyśmy tą dyskusję przeprowadzić, ale jak już dałem screeny z GPT to możemy tutaj przeprowadzić tą kwestię.

**Comment by jackpie2** [comment]
Jak chodzi o bibliotekę to w sumie pewnie są dedykowane do algorytmów hashujących, ale to wszystko jedno (tzn. dobór biblioteki jest mniej istotną kwestią teraz), dopóki hashe będą takie same dla takich samych ciągów z tym samym saltem. Główna trudność polega na tym, żeby używać tej samej funkcji hashującej co używa ta funkcja `crypt`, wiesz może czy to jest rzeczywiście bcrypt? Salt używa blowfisha z tego co widzę po odpowiedzi GPT, więc tu nie będzie problemu z odwzorowaniem. To ma znaczenie, żeby można było się logować jako już utworzeni testowi użytkownicy, których haslo zostało wygenerowane funkcją crypt.

**Comment by KarolBochenek** [comment]
Właściwie pgcrypto jest potrzebne tylko i wyłącznie wtedy, kiedy chcemy wprowadzić zahashowane hasło z poziomu DB, czyli INSERTa, natomiast jeśli zahashowane hasło idzie już z API (i jest hashowane przez np. to bcrypt), to DB tylko przechowuje to hasło i pgcrypto nie jest w ogóle używane. Tak więc możesz dobrać sobie bibliotekę, jaką uważasz za słuszną. Ważne tu jest tylko to, by był do DB wysyłany salt i zahashowane hasło jako osobne pola.

**Comment by jackpie2** [comment]
No tak wiem, ale w bazie są już użytkownicy których hash został wygenerowany przez pgcrypto. Żeby istniała opcja zalogowania się jako taki użytkownik muszę na API wygenerować ten hash i porównać go z hashem w DB, jak użyje innej funkcji hashującej niż ta używana przez pgcrypto to hashe będą się różnić mimo nawet identycznych haseł.

**Comment by KarolBochenek** [comment]
Tak, racja, to dummy trochę nam komplikuje niepotrzebnie, ale z tego co widzę jest to kompatybilne i możesz odczytać hash z pgcrypto zrobiony na DB przez bcrypt na Flasku. 
![Screenshot_2023-05-30-21-26-47-728_com android chrome](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/95887356/6ac45a25-05c6-4560-b75c-4e2cfa517bff)

**Comment by jackpie2** [comment]
Postaram się to zaraz przetestować

**Comment by KarolBochenek** [comment]
Jakoś nie współpracuje mi github we wklejaniu tego kodu w formacie jak Pan Bóg przykazał, mam nadzieję, że jakoś to sobie skopiujesz.

**Comment by jackpie2** [comment]
@KarolBochenek z tego co sprawdziłem to prawdopodobnie tam rzeczywiście używany jest algorytm bcrypt, w takim wypadku z tego co rozumiem kolumna salt jest zbędna, ponieważ jest już częścią całego "hasha":

![obraz](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/66798628/182ad00f-af11-40b1-a6c6-0a6c1e1c2af0)
(<https://en.wikipedia.org/wiki/Bcrypt>)

To by też się zgadzało z flask-bcrypt, bo działa mi na samym hashu hasła i nawet nie ma opcji podania/generacji soli.

**Comment by KarolBochenek** [comment]
Prawdopodobnie dla pgcrypto i dummies to salt będzie wymagane. Pozbycie się problemu jest po prostu usunięcie kolumny 'salt', wszystkiego z pgcrypto i nie wprowadzanie dummy recordów dla userów. Ewentualnie jeszcze sprawdzę, czy jest coś dla postgresa żeby działało tak jak bcrypt, czyli z samym hashem, który już ma w sobie salta.

**Comment by jackpie2** [comment]
No mi się właśnie wydaje że pgcrypto nie potrzebuje tej kolumny z saltem bo salt dodaje już do hasha hasła, tym bardziej że właśnie działa z flask-bcrypt bez tej kolumny zupełnie, no chyba że w dokumentacji jest inaczej.

**Comment by jackpie2** [comment]
Dla jasności, mam na myśli to, że wydaje mi się, że ani dla pgcrypto ani dla API nie jest potrzebna ta kolumna salt i wszystko może działać tak jak jest teraz tylko że bez niej:
![obraz](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/66798628/47492098-8e36-4512-a607-f8fded40f2b7)

Salt jest wymagane przy generowaniu hasha tutaj i z tym nie ma żadnego problemu po stronie api:
```sql
crypt('password123', gen_salt('bf'))
```

Bo z tego co rozumiem ta funkcja już automatycznie dodaje salt do hasha i stąd można ją odczytać (z kolumny hashed_password).

Problem jest tylko z kolumną salt która nie jest potrzebna api do weryfikacji hasła, bo salt jest już odczytywana z wcześniej wspomnianego hashed_password.

Swoją drogą to wydaje mi się, że tutaj i tak są dwie różne sole, bo wywołujesz gen_salt dwa razy, dlatego sól używana w crypt i sól w kolumnie salt prawdopodobnie nie pokrywają się:
![obraz](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/assets/66798628/81c14053-b946-4e56-bd21-a46f032773de)

To już mniej związany problem i nie przeszkadza w niczym obecnie, przez to że tej kolumny z solą API nie wykorzystuje.

**Comment by KarolBochenek** [comment]
Tak właśnie jest, z tego co widzę chatgpt mnie oszukał. Usuwam kolumnę salt i z insertów dummies usunę niepotrzebne podwójne solenie.
