### ISSUE TITLE
Dostosuj DB do przedyskutowanej kwestii hashowania haseł między DB a API

### ISSUE THREAD

**Issue by KarolBochenek** [Tomasz-Zdeb/Software-Engineering-Class-Project#144]
W zwiazku z #143 

## Kryteria Akceptacji

- [ ] Zmiany zostały zacommitowane
- [ ] Commit ze zmianami znajduje się na branchu `master`

**Comment by KarolBochenek** [comment]
@Tomasz-Zdeb myślisz, że warto wspomnieć w readme o kwestii hashowania i bezpieczeństwa haseł?

**Comment by Tomasz-Zdeb** [comment]
Zdecydowanie! :)
