### ISSUE TITLE
Zainicjalizuj projekt API

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Software-Engineering-Class-Project#23]
## Kryteria akceptacji zadania
- [x] Projekt API został zainicjalizowany
- [x] Testowy endpoint znajduje się w projekcie i jest sprawny
- [x] Dokumentacja oparta o Swagger jest dostępna dla testowego endpointa
- [x] Zmiany zostały zacommitowane
- [ ] Commit(y) ze zmianami znajduje się na branchu master

**Comment by jackpie2** [comment]
W związku z pojawieniem się wymogu dotyczącego dostępnej dokumentacji swagger dla API, proponowałbym skorzystać z dodatku do Flaska, który generuje taką dokumentację. Z pobieżnego researchu wynika, że ten jest całkiem popularny i rozwijany: [flask-restx](https://flask-restx.readthedocs.io/en/latest/), ([Github](https://github.com/python-restx/flask-restx)).

**Comment by wsliwa** [comment]
Popieram użycie Flask'a jak i skorzystanie z flask-restx.

**Comment by Tomasz-Zdeb** [comment]
- [ ] Do kryteriów akceptacji zadania dodałbym:
  - [ ] Testowy endpoint znajduje się w projekcie i jest sprawny
  - [ ] Dokumentacja oparta o Swagger jest dostępna dla testowego endpointa
