### ISSUE TITLE
Wybierz format komunikacji między frontendem a API

### ISSUE THREAD

**Issue by wsliwa** [Tomasz-Zdeb/Software-Engineering-Class-Project#34]
## Kryteria Akceptacji

- [x] format komunikacji został wybrany
- [x] Co najmniej jeden członek Teamu API przedstawił opinie
- [x] Co najmniej jeden członek Teamu Frontend przedstawił opinie
- [ ] Opis wybranego formatu komunikacji jest opisany w postaci sekcji w **README.md**

## Informacje

* Poniżej można proponować formaty komunikacji, wraz z ich krótkim opisem.

**Comment by wsliwa** [comment]
Tak jak już było poruszone na spotkaniu, proponuję format komunikacji json, ponieważ:

- jest prosty do zrozumienia
- jest bardzo popularny (nie trudno znaleźć przykłady użycia)
- łatwo parsowany przez różne języki programowania

**Comment by jackpie2** [comment]
Również jestem za jsonem.

**Comment by Tomasz-Zdeb** [comment]
- [ ] Do kryteriów akceptacji dodałbym też:
  - [ ] `Co najmniej jeden członek Teamu API przedstawił opinie`
  - [ ] `Co najmniej jeden członek Teamu Frontend przedstawił opinie`
- [ ] W kwestii obecnego pierwszego kryterium akceptacji: `wybranie formatu komunikacji` - nie jest ono zgodne z guidelineami, ponieważ nie opisuje stanu po realizacji zadania. Chodzi o coś w rodzaju: `format komunikacji został wybrany` @wsliwa mogłbyś to poprawić?

- [ ] Jeżeli nikt nie zaprzeczył przeciwko wyborowi JSONa, to proszę zapisać na samej górze issue w informacjach, że wybrany został JSON i oznaczyć podzadania a także całe Issue jako wykonane

**Comment by wsliwa** [comment]
@Tomasz-Zdeb issue został poprawiony.

### Do końca dzisiejszego dnia jest czas na inne propozycje. Brak propozycji/sprzeciwów, będzie oznaczał, że json uznany będzie za nasz format komunikacji i jutro go wpiszę do README.

**Comment by PWWP** [comment]
> Tak jak już było poruszone na spotkaniu, proponuję format komunikacji json, ponieważ:
> 
>     * jest prosty do zrozumienia
> 
>     * jest bardzo popularny (nie trudno znaleźć przykłady użycia)
> 
>     * łatwo parsowany przez różne języki programowania

Mam identyczne zdanie. Dodatkowo do samego JSON'a proponuje przekazywać wszystkie pola string pomiędzy frontem a api w formacie base64 żeby się nam coś później nie krzaczyło jak użytkownik wprowadzi quote w pole tekstowe.
