### ISSUE TITLE
Zorganizuj spotkanie dotyczące dalszego rozwoju projektu.

### ISSUE THREAD

**Issue by BlessedSamhain** [Tomasz-Zdeb/Software-Engineering-Class-Project#35]
- [x]  Stwórz ankietę, by ustalić najbardziej odpowiedni termin dla uczestników projektu
- [x] Termin spotkania został ustalony
- [x] Spotkanie zostało zorganizowane

**Comment by Tomasz-Zdeb** [comment]
- [ ] Dodanie labeli do zadań sprzed **Sprintu 4** @Tomasz-Zdeb
