### ISSUE TITLE
Skonfiguruj dokeryzację DB

### ISSUE THREAD

**Issue by BlessedSamhain** [Tomasz-Zdeb/Software-Engineering-Class-Project#39]
## Kryteria Akceptacji Zadania
- [x] Projekt zawiera konfigurację pozwalającą na uruchomienie DB w kontenerze Dockerowym
- [x] Konfiguracja uwzględnia wykonanie skryptów inicjalizujących DB
- [x] Konfiguracja wykorzystuje docker-compose.yml w root directory projektu
- [ ] Obraz został przetestowany
- [ ] Użycie Dockera zostało opisane w dokumentacji
- [ ] Zmiany zostały zacommitowane
- [ ] Commit ze zmianami znajduje się na branchu `master`

**Comment by BlessedSamhain** [comment]
# Dokeryzacja DB PostgreSQL
## Wstęp
Dokeryzacja bazy danych PostgreSQL może być korzystnym rozwiązaniem dla programistów i administratorów systemów, którzy chcą uniknąć problemów związanych z instalacją i konfiguracją bazy danych na różnych systemach operacyjnych. W tym celu można skorzystać z kontenerów _Docker_.

**Comment by Tomasz-Zdeb** [comment]
## Test Evidence
![2023-04-30 13-05-52](https://user-images.githubusercontent.com/62356875/235350523-caf3716c-a577-49c4-9a89-05f33b81acaa.gif)
