### ISSUE TITLE
Zorganizuj spotkanie dotyczące dalszego rozwoju projektu

### ISSUE THREAD

**Issue by ZimmerPM** [Tomasz-Zdeb/Software-Engineering-Class-Project#48]
## Kryteria Akceptacji Zadania

- [x] Stwórz ankietę co do wyboru terminu
- [x] Godzina spotkania jest znana
- [x] Spotkanie zostało zorganizowane

**Comment by Tomasz-Zdeb** [comment]
# Do realizacji w Sprincie 5

- [ ] Dodanie labeli do zadań sprzed **Sprintu 4** @Tomasz-Zdeb
- [ ] Implementacja issue dotyczące utworzenia modelu danych @KarolBochenek @wsliwa @xQuarellox  @jackpie2
- [ ] Dodanie do **Issue**  #18 kryterium akceptacji:
    * `Diagram w formacie obrazu znajduje się w pliku README.md`
- [ ] Implementacja @k4ciek @PWWP @ja2000no #42
- [ ] Stworzenie issue dotyczącego wyboru **bibliotek/frameworków** na **Frontend** @k4ciek @PWWP @ja2000no
- [ ] Implementacja issue dotyczącego wyboru **bibliotek/frameworków** na **Frontend** @k4ciek @PWWP @ja2000no
- [x] Upload nagrania ze spotkania nr 5 na dysk @ZimmerPM 
- [ ] Implementacja issue dotyczącego dokeryzacji **DB** @KarolBochenek @ZimmerPM @BlessedSamhain
- [ ] Implementacja issue, dotyczące dokeryzacji **API** @wsliwa @xQuarellox  @jackpie2 @ZimmerPM @BlessedSamhain
- [ ] Implementacja issue, dotyczące dokeryzacji **Frontendu** @k4ciek @PWWP @ja2000no @ZimmerPM @BlessedSamhain
- [ ] Organizacja następnego spotkania @ZimmerPM 
* **Implementacja wszelakich otwartych issues** @Tomasz-Zdeb @KarolBochenek @wsliwa @xQuarellox  @jackpie2 @k4ciek 
* **Przygotowanie propozycji utworzenia nowych issues** @Tomasz-Zdeb @KarolBochenek @wsliwa @xQuarellox  @jackpie2 @k4ciek @PWWP @ja2000no @ZimmerPM @BlessedSamhain 
## Specjalizacje

* DB @KarolBochenek 
* API @wsliwa @xQuarellox  @jackpie2
* FRONT @k4ciek @PWWP @ja2000no
* Dev-Ops @ZimmerPM @BlessedSamhain
