### ISSUE TITLE
Ustal specyfikację pierwszego endpointu

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Software-Engineering-Class-Project#51]
## Kryteria Akceptacji

- [ ] Specyfikacja pierwszego endpointu została ustalona

**Comment by jackpie2** [comment]
Jeśli dobrze pamiętam, to na którymś ze spotkań został zaproponowany endpoint "/note", który odpowiedzialny byłby za akcje na danej notatce, proponuję więc żeby był to pierwszy zaimplementowany endpoint. 

Taki endpoint mógłby wstępnie pozwalać na pobieranie danej notatki po ID oraz na tworzenie notatek w requeście post. 

Zapraszam do wypowiedzenia się na ten temat pozostałych osób z backendu @wsliwa @xQuarellox oraz frontendu @PWWP @k4ciek @ja2000no

**Comment by jackpie2** [comment]
Trzeba zdecydować czy chcemy rozbijać POST na np. POST, PUT, DELETE, czy zostajemy przy samym POST jako requeście modyfikującym zasób. Osobiście wydaje mi się że bardziej czytelniejsze byłoby rozbicie i nie wymagałoby przekazywania akcji w argumentach.

Moje propozycje:
Request GET mógłby wstępnie przyjmować jedynie ID notatki i zwracać wszystkie informacje o niej (te zawarte w diagramie ERD).

Requesty modyfikujące mogłyby przyjmować ID notatki, treść, tytuł i opis (jeśli wykonywane są jakieś akcje na nich) oraz ID katalogu. ID notatki byłby zawsze obowiązkowym argumentem, natomiast ID katalogu jedynie w przypadku tworzenia notatki. Tytuł mógłby być również obowiązkowy albo domyślny (np. Untitled note). Treść i opis mogłyby pozostać puste. Zwracany byłby status wykonania zadania, a w tym ewentualne błędy.

**Comment by Tomasz-Zdeb** [comment]
## 🔴POST VS 🟢POST/PUT/DELETE

W kwestii realizowania wszelkich operacji za pomocą metody POST, to bardzo zdecydowanie odradzam takie podejście. Powodów jest na prawdę wiele. Zasady tworzenia RESTowych API są bardzo dobrze opisane na stronie: 
- https://restfulapi.net/

ChatGPT pomógł mi sformułować powody przeciwko realizowaniu wszystkich funkcjonalności za pomocą metody POST:

> In RESTful API design, HTTP methods such as POST, DELETE, and PUT have specific meanings and purposes. While it is technically possible to use the POST method to perform the functionality of all three methods, it is generally not recommended for the following reasons:
> - Semantics: HTTP methods have specific meanings that are understood by both clients and servers. When a client sends a POST request, it indicates that it is creating a new resource on the server. In contrast, a DELETE request indicates that the client wants to delete an existing resource, and a PUT request indicates that the client wants to update an existing resource. By using the appropriate HTTP method for each action, it makes the API more intuitive and easier to understand for both the client and the server.
> - Caching: HTTP methods also have implications for caching. For example, if a client sends a POST request, it is generally not cacheable, whereas a PUT or DELETE request may be cacheable. This can impact performance and scalability of the API.
> - Idempotence: HTTP methods such as PUT and DELETE are idempotent, meaning that performing the same operation multiple times will have the same effect as performing it once. This is not necessarily true for POST requests, which can lead to unintended consequences if the same request is sent multiple times.
> - Security: Using the correct HTTP method for each action can also improve security. For example, if a client sends a DELETE request with sensitive information in the URL query string, that information may be logged by proxies or servers along the way. In contrast, using the HTTP DELETE method ensures that the sensitive information is not logged or stored.

> In summary, while it is technically possible to use the POST method to perform the functionality of all three methods, using the appropriate HTTP method for each action makes the API more intuitive, easier to understand, and can improve performance, scalability, security, and idempotence.

## Ustalenie specyfikacji

Ustalenie specyfikacji polega przede wszystkim na zaprojektowaniu endpointu, podejściem które ja używam polega na wypisaniu w punktach każdej metody i opisaniu w jej podpunktach wszelkich informacji na jej temat, tj. przyjmowane argumenty, format zwracanych danych, zwracane kody operacji itp. (ChatGPT na pewno pomoże w zaprojektowaniu takowych).

Jak rzuciłem okiem na diagram ERD to powiedziałbym że metoda GET powinna mieć obowiązkowy parametr określający ID użytkownika oraz opcjonalne parametry pozwalające na przesłanie wartości id tabel z którymi notatka jest w relacji, tj. aby można było pobrać wszystkie notatki po tagu, katalogu lub usuniętych.

Gdy specyfikacja będzie wypunktowana to będzie to przejrzyście i dzięki temu łatwiej będzie dyskutować na jej temat, dlatego zachęcam do zastosowanie takiego formatu :)

### Dygresja

BTW ambitną i jednoznaczną alternatywą zapisu w punktach jest stworzenie specyfikacji wg. formatu OpenAPI w pliku yaml

**Comment by jackpie2** [comment]
# GET

## Argumenty

### Wymagane

* `note_id` - ID notatki (int)

## Wartości zwracane

* `catalog_id` - ID katalogu (int)
* `title` - Tytuł notatki (string)
* `description` - Opis notatki (string)
* `body` - Treść notatki (string)
* `created_date` - Data utworzenia notatki (timestamp)
* `updated_date` - Data ostatniej modyfikacji notatki (timestamp)

## Kody błędów

* `404` - Notatka nie istnieje

# POST

## Argumenty

### Wymagane

* `user_id` - ID użytkownika (int)

### Opcjonalne

* `title` - Tytuł notatki (string), domyślnie np. "Nowa notatka/Untitled" (lub jako wymagany, do ustalenia)
* `description` - Opis notatki (string), domyślnie `null`
* `body` - Treść notatki (string), domyślnie `null`
* `catalog_id` - ID katalogu (int), domyślnie `null`

## Wartości zwracane

* `note_id` - ID notatki (int)
* `201` - wiadomość o powodzeniu

## Kody błędów

* `400` - Błędne dane (np. `user_id` nie został podany)
* `404` - Dane nie istnieją (np. `catalog_id` albo `user_id` nie istnieje)

# PUT

## Argumenty

### Wymagane

* `note_id` - ID notatki (int)

### Opcjonalne

* `title` - Tytuł notatki (string)
* `description` - Opis notatki (string)
* `body` - Treść notatki (string)
* `catalog_id` - ID katalogu (int)

## Wartości zwracane

* `200` - wiadomość o powodzeniu

## Kody błędów

* `400` - Błędne dane (np. `note_id` nie został podany)
* `404` - Dane nie istnieją (np. `note_id` nie istnieje)

# DELETE

## Argumenty

### Wymagane

* `note_id` - ID notatki (int)

## Wartości zwracane

* `200` - wiadomość o powodzeniu

## Kody błędów

* `400` - Błędne dane (np. `note_id` nie został podany)
* `404` - Dane nie istnieją (np. `note_id` nie istnieje)


Taka jest moja wstępna propozycja specyfikacji. Póki co bez elementów autoryzacji użytkowników, bo do tego będzie trzeba wykonać później dodatkowy research. Zapraszam do dyskusji nad ewentualnymi poprawkami (@Tomasz-Zdeb @PWWP @ja2000no @xQuarellox @wsliwa @k4ciek). Wiem też, że wcześniej padła propozycja, żeby kodować wartości tekstowe przekazywane przez użytkownika w base64, także co do tego również wypadałoby podjąć decyzję.

**Comment by Tomasz-Zdeb** [comment]
Kody w HTTP odnoszą się nie tylko do błędów, a ogólnie do statusu requesta:

> HTTP return code and returned content are two different things in the context of a client-server communication over the HTTP protocol.

> HTTP return code, also known as HTTP status code, is a three-digit numerical code that is returned by the server to the client to indicate the status of the requested resource. The HTTP return code is part of the HTTP response header and it indicates whether the request was successful or not, whether the resource is available or not, whether the client needs to authenticate or not, and so on. Some common HTTP return codes include 200 OK (which means the request was successful), 404 Not Found (which means the requested resource was not found), and 500 Internal Server Error (which means the server encountered an error while processing the request).

> Returned content, on the other hand, is the actual data that is returned by the server to the client in response to the request. The returned content is part of the HTTP response body and it can be in various formats such as HTML, JSON, XML, plain text, or binary data depending on the type of resource being requested and the content negotiation between the client and the server.

> In summary, HTTP return code indicates the status of the request, while returned content is the actual data that is returned by the server in response to the request.

**Comment by jackpie2** [comment]
Zmodyfikowałem opis specyfikacji. Teraz wszystkie kody odpowiedzi zawarte są pod jednym nagłówkiem.

**Comment by Tomasz-Zdeb** [comment]
Według mnie specyfikacja została sporządzona w sposób wyczerpujący. Jeżeli ktoś ma jeszcze jakieś uwagi to bardzo proszę, w przeciwnym razie warto zamknąć tego taska i przejść do implementacji endpointa

**Comment by wsliwa** [comment]
Również dla mnie wygląda dobrze, można zamknąć i przejść do implementacji.
