### ISSUE TITLE
Wybierz bibliotekę do obsługi bazy danych

### ISSUE THREAD

**Issue by wsliwa** [Tomasz-Zdeb/Software-Engineering-Class-Project#57]
## Kryteria Akceptacji

- [x] Zostały przedstawione propozycje bibliotek
- [x] Biblioteka została wybrana
- [x] Biblioteka została opisana w README

## Informacje

* Baza danych jest w technologii PostgreSQL

**Comment by wsliwa** [comment]
Po przeszukaniu internetu na temat bibliotek dla PostgreSQL w python'nie znalazłem następujące informacje:

- Psycopg2:  to popularna biblioteka Pythona, która umożliwia łączenie się z bazą danych PostgreSQL. Jest to najbardziej popularna biblioteka do pracy z PostgreSQL w Pythonie. 
- SQLAlchemy: to popularny ORM (Object Relational Mapper) dla Pythona. Umożliwia on pracę z różnymi bazami danych, w tym z PostgreSQL, za pomocą bardziej abstrakcyjnego interfejsu. Działa świetnie z Flaskiem, a także z innymi popularnymi frameworkami.
- asyncpg: wydajna biblioteka Pythona do łączenia się z PostgreSQL w sposób asynchroniczny.
- Tortoise-ORM: to łatwy w obsłudze ORM dla Pythona, który obsługuje PostgreSQL i inne bazy danych.

**Comment by wsliwa** [comment]
Nie pracowałem jeszcze z żadną z tych bibliotek, ale najczęstszym sposobem łączenia się z bazą PostgreSQL, który widziałem, był przy użyciu Psycopg2, więc w tym kierunku bym szedł, jeśli nie będziecie mieli innych preferencji.

**Comment by jackpie2** [comment]
W związku z naglącym terminem ukończenia #24, pierwszy endpoint jest już wstępnie zaimplementowany w #56, w oparciu o SQLAlchemy. Jest to jednak wciąż draft, więc jeśli zdecydujemy o innej bibliotece, to nie widzę problemu żeby zmodyfikować tę implementację. Potencjalną zaletą SQLAlchemy byłby brak konieczności pisania zapytań SQL, a jedynie operowanie na Pythonowych obiektach. Wstępnie próbowałem też implementować ten endpoint w Psycopg2, ale według mnie złożoność logiki była większa, głównie przez konieczność pisania "niskopoziomowych" zapytań SQL.

**Comment by jackpie2** [comment]
Jeśli nie będzie zastrzeżeń co do korzystania dalej z SQLAlchemy, to w najbliższym czasie przygotuje #56 do mergowania i po akceptacji zmerguje.

@wsliwa @xQuarellox

**Comment by wsliwa** [comment]
Nie, nie mam z tym problemu. W takim razie zakładam, że wybraną biblioteką jest SQLAlchemy i jutro postaram się dodać PR z informacją w README.

Jeszcze takie pytanie @Tomasz-Zdeb dodać do API osobne README, na informacje dotyczące jedynie API, czy dodać to do głównego?

**Comment by Tomasz-Zdeb** [comment]
Super, dzięki za szybką odpowiedź! 🫡

Jeżeli chodzi o kwestie związane stricte z danym komponentem to oddzielny markdown dokument w directory tego komponentu jest moim zdaniem dobrym rozwiązaniem (ja stworzyłem taką dokumentację ``DOCS.md`   w directory projektu frontendowego)

**Comment by wsliwa** [comment]
W DOCS.md została opisana wybrana biblioteka (więcej szczegółów w PR #73).

Jako, że było to ostatnie zadanie i wszystkie kryteria akceptacji są spełnione to zamykam issue.
