### ISSUE TITLE
Wybierz framework do testów API

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Software-Engineering-Class-Project#61]
## Kryteria Akceptacji

- [x] Framework do testów został wybrany

**Comment by jackpie2** [comment]
W dokumentacji flaska podany jest przykład, wykorzystujący PyTest: [link](https://flask.palletsprojects.com/en/2.3.x/testing/). PyTest wydaje się być jednym z najbardziej popularnych frameworków, dlatego proponuję z niego skorzystać.

**Comment by wsliwa** [comment]
Jak dla mnie PyTest jest ok.

**Comment by jackpie2** [comment]
Zostańmy zatem przy PyTeście.
