### ISSUE TITLE
Dodaj nieprzezroczyste tlo diagramowi zwiazkow encji

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Software-Engineering-Class-Project#92]
## Kryteria Akceptacji

- [x] Wszystkie elementy diagramu związków encji mają nieprzeźroczyste tła
- [x] Zmiany zostały zacommitowane
- [ ] Commit ze zmianami znajduje się na branchu `master`

## Kontekst

Aktualnie w przypadku ciemnego motywu, większość diagramu nie jest czytelna ze wzgledu na przeźroczystość tabel

![image](https://user-images.githubusercontent.com/62356875/235724863-c2d7d55a-25eb-4812-a0e7-3726d225a79e.png)

**Comment by KarolBochenek** [comment]
@Tomasz-Zdeb sprawdź proszę [tutaj](https://github.com/Tomasz-Zdeb/Software-Engineering-Class-Project/blob/92-dodaj-nieprzezroczyste-tlo-diagramowi-zwiazkow-encji/DB/ERD-diagram.drawio.png) na dark theme, czy jest to ten efekt, o który chodzi.

**Comment by Tomasz-Zdeb** [comment]
Ok teraz tło jest zabarwione :+1:  Co prawda nie widać relacji, ale aby to osiągnąć musielibyśmy umieścić zabarwiony prostokąd pod przestrzenią całego diagramu
